import type { BlankNode, DefaultGraph, Literal, NamedNode, Quad, Term, Variable } from '@rdfjs/types';

function compareBlankNodes(this: BlankNode, other: Term | null | undefined): boolean {
    return this.termType === other?.termType && this.value === other.value;
}

function compareVariables(this: Variable, other: Term | null | undefined): boolean {
    return this.termType === other?.termType && this.value === other.value;
}

function compareNamedNodes(this: NamedNode, other: Term | null | undefined): boolean {
    return this.termType === other?.termType && this.value === other.value;
}

function compareLiterals(this: Literal, other: Term | null | undefined): boolean {
    return (
        this.termType === other?.termType &&
        this.value === other.value &&
        (this.language ?? '') === (other.language ?? '') &&
        this.datatype.equals(other.datatype)
    );
}

function compareQuads(this: Quad, other: Term | null | undefined): boolean {
    return (
        this.termType === other?.termType &&
        this.subject.equals(other.subject) &&
        this.predicate.equals(other.predicate) &&
        this.object.equals(other.object)
    );
}

function compareDefaultGraphs(this: DefaultGraph, other: Term | null | undefined): boolean {
    return this.termType === other?.termType && this.value === other.value;
}

function patchTermEquals(term: NamedNode | Literal | BlankNode | Quad | Variable | DefaultGraph): void {
    switch (term.termType) {
        case 'NamedNode':
            term.equals = compareNamedNodes;
            break;
        case 'Literal':
            term.equals = compareLiterals;
            term.datatype.equals = compareNamedNodes;
            break;
        case 'BlankNode':
            term.equals = compareBlankNodes;
            break;
        case 'Variable':
            term.equals = compareVariables;
            break;
        case 'Quad':
            term.equals = compareQuads;
            patchTermEquals(term.object);
            patchTermEquals(term.subject);
            patchTermEquals(term.predicate);
            patchTermEquals(term.graph);
            break;
        case 'DefaultGraph':
            term.equals = compareDefaultGraphs;
            break;
    }
}

/**
 * Patches quads generated by the jsonld library to conform with rdfjs types.
 *
 * @See https://github.com/digitalbazaar/jsonld.js/issues/243
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/explicit-module-boundary-types
export function patchJsonLDQuads(quads: any): Quad[] {
    for (const quad of quads) {
        quad.termType = 'Quad';
        patchTermEquals(quad);
    }

    return quads;
}
